apiVersion: v1
kind: Namespace
metadata:
  name: helllooo-prod
  labels:
    environment-id: env_8d5921f4-5f88-479d-8dfb-bb3c2a179ebf
    project-id: project_2e76dd4a-6274-48ff-a62f-a6c42bd3cb0f
    project-name: Helllooo
    environment-name: prod
    organization-id: org_2efb54be-5fb5-4780-ad77-0878afc1614d
