apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: latest
      cpuRequestMili: 100
      cpuLimitMili: 200
      memoryRequestMb: 100
      memoryLimitMb: 200
      args: []
      command: []
      configMounts: []
      applicationPorts: []
      healthChecks: []
      name: mist-main
  minReplicas: 1
  maxReplicas: 5
  terminationGracePeriodSeconds: 30
  nodeSelector:
    kubernetes.io/hostname: my-node-name
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: praisethelord
    env: production
    applicationId: app_a1204ab2-b2d8-4745-9671-f42882fde1df
    projectId: project_2e76dd4a-6274-48ff-a62f-a6c42bd3cb0f
    organizationId: org_2efb54be-5fb5-4780-ad77-0878afc1614d
    environmentId: env_8d5921f4-5f88-479d-8dfb-bb3c2a179ebf
    environmentName: prod
  horizontalAutoScalingRules:
    - ruleType: cpu
      percentage: 80
  volumes:
    - name: my-volume
      type: PersistentVolumeClaim
      pvc:
        claimName: my-claim
  type: service
  serviceType: LoadBalancer
  namespace: foo
  name: mist
